### ISSUE TITLE
Break down "Land use" layer into multiple layers

### ISSUE THREAD

**Issue by saylorsd** [WPRDC/green-dream#11]
> “Land Use” a as subcategory maybe its own category. Some layers under it now are natural features such as woodland but others are more of a manmade land use such as athletic field (some are plastic turf) and nursery. If we use “Land Use” there is a very long list of uses as per zoning or actual use – used car lot, cemetery, office building, road, …. If we use “Land Cover” we could possibly winnow that down to something as simple as pervious/impervious. What do we need? And what is readily available?

Make `Land Use` a category

**Comment by AlyFear** [comment]
Dropping the request, this Land Use dataset isn't the most useful anyway.
