### ISSUE TITLE
Legend Pop up exceeds page 

### ISSUE THREAD

**Issue by AlyFear** [WPRDC/green-dream#14]
When most to all the datasets are open, the legend exceeds the page,  can it be set to dynamic or as a floating pop up that can be moved out of the way?

**Comment by saylorsd** [comment]
my current idea for a solution to this is to have a button that can toggle displaying the legend.

I think i'll also limit it's height and add a scrollbar if it gets too big.  Any thoughts, @AlyFear?

**Comment by saylorsd** [comment]
I like that.  I'll try that first.  Thanks!

**Comment by saylorsd** [comment]
I limited the height of the legend and set a scroll bar so we can have a solution for now.  I've made a new issue for looking into better ways to handle the legend.  I'll experiment with information panels and such for that one.

@AlyFear Please take a look at the staging site and let me know if this is suitable for now.

**Comment by AlyFear** [comment]
Steve,
I don’t think the staging site updated, Im in the Green Test map and the legend has the same issues.

I see the Open Space color updates, so it’s got part of your new stuff covered.

Alyson Fearon
Community Conservation Director
Allegheny Land Trust

416 Thorn Street  |  Sewickley, PA  |  15143
Office: 412.741.2750x204  |  Mobile: 314.556.4892

www.alleghenylandtrust.org<http://www.alleghenylandtrust.org/>
facebook<https://www.facebook.com/alleghenylandtrust> | flickr<https://www.flickr.com/photos/68211232@N02/albums> | instagram<https://instagram.com/alleghenylandtr/>
linkedin<http://www.linkedin.com/company/allegheny-land-trust> | pinterest<https://www.pinterest.com/AlleghenyLandTr/> | twitter<https://twitter.com/AlleghenyLandTr> | youtube<https://www.youtube.com/user/AlleghenyLandTrust/videos>
[ALTlogo_esig_small][accreditationseal_small]
