### ISSUE TITLE
muncipality layer producing grid on map

### ISSUE THREAD

**Issue by saylorsd** [WPRDC/green-dream#18]

**Comment by AlyFear** [comment]
I was just playing around on this and on the east side of the map Monroeville still has it, I can't tell you which layer of zoom bc the tool doesn't give me the zoom levels sorry

**Comment by saylorsd** [comment]
I think this may have resolved itself or more precisely, carto had some issue and fixed it.

@AlyFear can you confirm that this is fixed for you and we can close this one.

**Comment by AlyFear** [comment]
Agree this appears to have resolved
