### ISSUE TITLE
Come up with better layer group names

### ISSUE THREAD

**Issue by saylorsd** [WPRDC/green-dream#7]
> Urban Green “Features” implies something physical. These lawyers are basically plans or land use perhaps except for 3RWW GI and garden sites. Maybe a new “Community Greening Projects” group needs to be created? And maybe Urban Green Features should be relabeled “Plans” and could later include Community Plans. Also, since county parks are included the qualifier “Urban” should be deleted.

**Comment by AlyFear** [comment]
New Layer Groupings-Also on Google Sheet
Borders and Infrastructure
Green Space Features (Current)
Green Space Features (Suggested or Proposed)
Mobility
